name: Continuous Integration and Delivery

on: 
  push:
    branches: [main]

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 51.21.135.58
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            ls
