name: Continuous Integration and Delivery

on: 
  push:
    branches: [main]

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Execute remote SSH command using password
        uses: appleboy/ssh-action@v1
        with:
          host: 51.21.135.58
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            export PATH=$PATH:/usr/bin
            export NVM_DIR="$HOME/.nvm"
            source $NVM_DIR/nvm.sh
            nvm use 24
            
            cd 100xdevs-ci-cd
            git pull origin main
            npm install
            npm run build
            npm run start
